--Alex Fink
DROP TABLE GG_SERVICE CASCADE CONSTRAINTS;
DROP TABLE GGEMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE OWNED_PROPERTY CASCADE CONSTRAINTS;
DROP TABLE OWNER CASCADE CONSTRAINTS;
DROP TABLE PROPERTY_SERVICE CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

-- Create CUSTOMER table
CREATE TABLE CUSTOMER (
    UserID Int NOT NULL,
    Name VarChar(50) NOT NULL,
    Email VarChar(100) NOT NULL,
    Phone VarChar(12) NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(UserID)
);

-- Create PRODUCT table
CREATE TABLE PRODUCT (
    ProductID Int NOT NULL,
    "Type" VarChar(15) NOT NULL,
    Price NUMBER NOT NULL,
    Gender VarChar(1) NOT NULL,
    Shipping_Address Char(50) NOT NULL,
    Brand VarChar(50) NOT NULL,
    "Size" VarChar(15) NOT NULL,
    Color VarChar(15) NOT NULL,
    CONSTRAINT PRODUCT_PK PRIMARY KEY(ProductID)
);

-- Create CART table
CREATE TABLE CART (
    OrderID Int NOT NULL,
    UserID Int NOT NULL,
    ProductID Int NOT NULL,
    Total NUMBER NOT NULL,
    Payment_Method VarChar(12) NOT NULL,
    Shipping_Address VarChar(50) NOT NULL,
    CONSTRAINT CART_PK PRIMARY KEY(OrderID),
    CONSTRAINT CART_CUST_FK FOREIGN KEY (UserID) REFERENCES CUSTOMER(UserID),
    CONSTRAINT CART_ITEM_FK FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- Create ADDRESS table
CREATE TABLE ADDRESS (
    AddressID Int NOT NULL,
    AddressNo Int NOT NULL,
    City VarChar(25) NOT NULL,
    Street VarChar(25) NOT NULL,
    Zip Int NOT NULL,
    State Char(25) NOT NULL,
    User_ID Int NOT NULL,
    CONSTRAINT ADDRESS_PK PRIMARY KEY(AddressID),
    CONSTRAINT ADDRESS_USER_FK FOREIGN KEY (User_ID) REFERENCES CUSTOMER(UserID)
);

-- Create PAYMENT table
CREATE TABLE PAYMENT (
    PayID Int NOT NULL,
    Pin Int NULL,
    Card_no Int NULL,
    Method Char(25) NOT NULL,
    Gift_Card_Code Int NULL,
    UserID Int NOT NULL,
    CONSTRAINT PAYMENT_PK PRIMARY KEY (PayID),
    CONSTRAINT PAYMENT_USER_FK FOREIGN KEY (UserID) REFERENCES CUSTOMER(UserID)
);


